# name: Deployment of React-Shopify
# on:
#   push:
#     branches:
#       - Innova-inspection
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [20.x]
#     steps:
#       - uses: actions/checkout@v1
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Install Packages
#         run: npm install
#       - name: cypress install
#         run: npm i cypress
#       # - name: Verify Cypress
#       #   run: npx cypress verify
#   cypress-run:
#     runs-on: ubuntu-latest
#     container:
#       image: cypress/included:13.13.3
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Run Cypress tests
#         run: npx cypress run --browser chrome --spec "cypress/e2e/e2eTest/main.cy.js"
name: Cypress Tests

on:
  push:
    branches:
      - Innova-Inspection
  # pull_request:
  #   branches:
  #     - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
